services:
  student_lb:
    container_name: student_lb
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - student_service_1
      - student_service_2

  gateway_service:
    container_name: APIgateway_service
    build:
      context: ./APIGateway_Microservice
      dockerfile: Dockerfile

    ports:
      - "80:3000"

    environment:
      - JWT_SECRETE=${JWT_SECRETE}
    depends_on:
      - auth_service
      - librarian_service
      - student_lb

  auth_service:
    container_name: authentication_service
    build:
      context: ./Authentication_Microservice
      dockerfile: Dockerfile

    environment:
      - JWT_SECRETE=${JWT_SECRETE}
      - MONGO_URI=${MONGO_URI}

  librarian_service:
    container_name: librarian_service
    build:
      context: ./Librarian_Microservice
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}

  student_service_1:
    container_name: student_service_1
    build:
      context: ./Student_Microservice
      dockerfile: Dockerfile
    hostname: student1
    restart: on-failure
    environment:
      - MONGO_URI=${MONGO_URI}

  student_service_2:
    container_name: student_service_2
    build:
      context: ./Student_Microservice
      dockerfile: Dockerfile
    hostname: student2
    restart: on-failure
    environment:
      - MONGO_URI=${MONGO_URI}

networks:
  default:
    name: library-network
