events {
    worker_connections 1024;
}

http {
    upstream student_nodes {
        server student_service_1:5002;
        server student_service_2:5002;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://student_nodes;
        }
    }
}